USING_ARDUINO_BOARD: equ 0
DEBUG_DSKIO: equ 0
WAIT_KEY_ON_INIT: equ 0
INVERT_CTRL_KEY: equ 0
DISABLE_OTHERS_BY_DEFAULT: equ 0
IMPLEMENT_PANIC_BUTTON: equ 1

ROM_BANK_0: equ 0
ROM_BANK_1: equ 1

USE_ASCII8_ROM_MAPPER: equ 0
