VERSION=2.1.1
SRC_PATH=$(dirname "$0")
SRC_FILE=${SRC_PATH}/rookiefdd.asm
DEST_DIR=${SRC_PATH}/bin
BASE_DEST_FILE=${DEST_DIR}/rookiefdd${VERSION}
N80_ARGS="--direct-output-write"

mkdir -p $DEST_DIR

echo RookieDrive FDD ROM version $VERSION
echo

N80 $SRC_FILE ${BASE_DEST_FILE}_normal.rom $N80_ARGS
N80 $SRC_FILE ${BASE_DEST_FILE}_inverted_ctrl.rom -ds INVERT_CTRL_KEY $N80_ARGS
N80 $SRC_FILE ${BASE_DEST_FILE}_exclusive.rom -ds DISABLE_OTHERS_BY_DEFAULT $N80_ARGS
N80 $SRC_FILE ${BASE_DEST_FILE}_alt_ports.rom -ds USE_ALTERNATIVE_PORTS $N80_ARGS
N80 $SRC_FILE ${BASE_DEST_FILE}_exclusive_inverted_ctrl.rom -ds INVERT_CTRL_KEY,DISABLE_OTHERS_BY_DEFAULT $N80_ARGS
N80 $SRC_FILE ${BASE_DEST_FILE}_alt_ports_inverted_ctrl.rom -ds USE_ALTERNATIVE_PORTS,INVERT_CTRL_KEY $N80_ARGS
N80 $SRC_FILE ${BASE_DEST_FILE}_alt_ports_exclusive.rom -ds USE_ALTERNATIVE_PORTS,DISABLE_OTHERS_BY_DEFAULT $N80_ARGS
N80 $SRC_FILE ${BASE_DEST_FILE}_alt_ports_exclusive_inverted_ctrl.rom -ds USE_ALTERNATIVE_PORTS,DISABLE_OTHERS_BY_DEFAULT,INVERT_CTRL_KEY $N80_ARGS
